config-version: 3

modules:
  player-data:
    enabled: true
  chat:
    enabled: true
  gamemode:
    enabled: true
  punishments:
    enabled: true
  warns:
    enabled: true
  integrations:
    enabled: true

theme:
  fcolors:
    "1": "color:#4FD6FF"
    "2": "color:#4FFF88"
    "3": "color:#FF4F4F"

storage:
  type: SQLITE
  sqlite:
    file: "database/auriongo.db"
  mysql:
    host: "127.0.0.1"
    port: 3306
    database: "auriongo"
    username: "root"
    password: "password"
    parameters: "useSSL=false&serverTimezone=UTC&characterEncoding=utf8"
  mariadb:
    host: "127.0.0.1"
    port: 3306
    database: "auriongo"
    username: "root"
    password: "password"
    parameters: "useSSL=false&useUnicode=true&characterEncoding=utf8"
